### ISSUE TITLE
Test Swerve to find remaining constants

### ISSUE THREAD

**Issue by nubmonkey** [Decatur-High-GlobalDynamics/FRC-2023-Team-4026#18]
We need to use a combination of sysid and regular testing

We need to test/get the following constants:
- Module-specific ports 
- angleOffsets (read 364 documentation for how)
- Angle motor PID values
- Drive motor PID vlaues
- maxSpeed/maxAngular Velocity
- Drive characterization values (sysid)

After getting constants and fully testing swerve as a pancake, we will uncomment the following:
- subsystem inits in RobotContainer
- subsystem test stuff in Robot.java
- ALL secondary button mappings
- autos(will need to be revised fully anyway) and auto selection
- auto logging

**Comment by renatodellosso** [comment]
Most constants have been found. Need to double-check/resolve the following:
-
